In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

DATA_FOLD = Path.cwd().parent
DATA_DIR = DATA_FOLD / "data" / "Food delivery.csv"

df = pd.read_csv(DATA_DIR)
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [51]:
df.shape

(45593, 20)

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  str
 3   Delivery_person_Ratings      45593 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  45593 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  str
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  str
dtypes: float64(4), int64(1), str(15)
memory usage: 11.9 MB

In [53]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [54]:
df[df['Weatherconditions']=='conditions NaN']

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
74,0xa9f,BANGRES13DEL01,NaN,NaN,12.935662,77.614130,12.975662,77.654130,11-03-2022,NaN,15:30:00,conditions NaN,NaN,1,Drinks,scooter,0,No,Metropolitian,(min) 19
120,0x6e2,VADRES06DEL01,NaN,NaN,22.312790,73.170283,22.422790,73.280283,02-04-2022,NaN,18:25:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,(min) 25
250,0x1b50,PUNERES16DEL01,NaN,NaN,18.536718,73.830327,18.646718,73.940327,08-03-2022,NaN,21:25:00,conditions NaN,NaN,3,Buffet,motorcycle,1,Yes,Urban,(min) 43
348,0x4c1,BANGRES13DEL02,NaN,NaN,12.935662,77.614130,13.065662,77.744130,02-03-2022,NaN,00:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,(min) 26
425,0xc003,DEHRES13DEL02,NaN,NaN,-30.366322,-78.070453,30.496322,78.200453,18-02-2022,NaN,22:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,(min) 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45332,0x2950,VADRES04DEL02,50,6,0.000000,0.000000,0.020000,0.020000,19-03-2022,NaN,10:40:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Urban,(min) 28
45394,0xdc4,RANCHIRES02DEL03,NaN,NaN,0.000000,0.000000,0.030000,0.030000,05-03-2022,NaN,17:25:00,conditions NaN,NaN,3,Buffet,bicycle,1,No,Metropolitian,(min) 21
45504,0x461,BANGRES07DEL02,NaN,NaN,-12.978453,-77.643685,12.998453,77.663685,17-03-2022,NaN,09:30:00,conditions NaN,NaN,3,Meal,scooter,1,No,NaN,(min) 24
45518,0x863,INDORES05DEL01,NaN,NaN,22.727021,75.884167,22.737021,75.894167,19-03-2022,NaN,11:40:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,(min) 25
45519,0xd0be,AGRRES07DEL01,NaN,NaN,27.160934,78.044095,27.170934,78.054095,13-02-2022,NaN,09:05:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Urban,(min) 17

In [55]:
df['Weatherconditions'].value_counts()

Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
conditions NaN            616
Name: count, dtype: int64

In [56]:
#fixing the time_taken 

# a = "(min) 24"

# print(a.split(")")[1])


df["Time_taken(min)"] = df["Time_taken(min)"].apply(lambda x : int(x.split(")")[1]))

In [57]:
df["Time_taken(min)"]

0        24
1        33
2        26
3        21
4        30
         ..
45588    32
45589    36
45590    16
45591    26
45592    36
Name: Time_taken(min), Length: 45593, dtype: int64

In [58]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,conditions Windy,High,1,Meal,motorcycle,0,No,Metropolitian,32
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,conditions Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,36
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,conditions Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,16
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,conditions Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,26
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,conditions Fog,Medium,2,Snack,scooter,1,No,Metropolitian,36

In [59]:
df.columns

# columns should int -> ['Delivery_person_ID', 'Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude', 'Restaurant_longitude', 'Delivery_location_latitude', 'Delivery_location_longitude', 'Vehicle_condition','multiple_deliveries' ]

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='str')

In [60]:
df["Weatherconditions"] = df["Weatherconditions"].apply(lambda x : x.split(" ")[1])

In [61]:
df["Weatherconditions"]

0             Sunny
1            Stormy
2        Sandstorms
3             Sunny
4            Cloudy
            ...
45588         Windy
45589         Windy
45590        Cloudy
45591        Cloudy
45592           Fog
Name: Weatherconditions, Length: 45593, dtype: str

In [62]:
df.select_dtypes(include="object").columns

C:\Users\Divya S. Shekhawat\AppData\Local\Temp\ipykernel_11856\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Type_of_order', 'Type_of_vehicle', 'multiple_deliveries', 'Festival',
       'City'],
      dtype='str')

In [63]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()
    df[col] = df[col].replace("NaN", np.nan)

C:\Users\Divya S. Shekhawat\AppData\Local\Temp\ipykernel_11856\410968054.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          43739 non-null  str
 3   Delivery_person_Ratings      43685 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          44600 non-null  str
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(4), int64(2), str(14)
memory usage: 10.9 MB

Imputing the remaining missing values
Two column types need two different strategies:

 ``Numeric columns → fill with the median. The median is robust to outliers and skew, so a few extreme values will not drag the fill value around the way the mean would.``
 
``Categorical columns → fill with the mode (the most frequent category), which is the only sensible "average" for a non-numeric field.``

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          43739 non-null  str
 3   Delivery_person_Ratings      43685 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          44600 non-null  str
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(4), int64(2), str(14)
memory usage: 10.9 MB

In [66]:

# Force genuinely numeric columns to numeric dtype; errors='coerce' turns any
# leftover bad values into NaN instead of raising, so we can impute them next
for col in ['Delivery_person_Age','Delivery_person_Ratings','multiple_deliveries'] :
  df[col]=pd.to_numeric(df[col],errors='coerce')

In [67]:
# Numeric columns: fill missing values with the median (robust to outliers/skew)
for col in ['Delivery_person_Age','Delivery_person_Ratings','multiple_deliveries'] :
  df[col]=df[col].fillna(df[col].median())

In [68]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,Sunny,High,2,Snack,motorcycle,0.0,No,Urban,24
1,0xb379,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,Stormy,Jam,2,Snack,scooter,1.0,No,Metropolitian,33
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,Sandstorms,Low,0,Drinks,motorcycle,1.0,No,Urban,26
3,0x7a6a,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,Sunny,Medium,0,Buffet,motorcycle,1.0,No,Metropolitian,21
4,0x70a2,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,Cloudy,High,1,Snack,scooter,1.0,No,Metropolitian,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45588,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45589,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45590,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45591,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45592,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [69]:
# Columns having null values
null_cols = df.columns[df.isnull().any()].tolist()

# Integer columns with null values
int_cols = df[null_cols].select_dtypes(include=['int', 'int64']).columns.tolist()

# Object columns with null values
obj_cols = df[null_cols].select_dtypes(include=['object']).columns.tolist()

print("Integer columns:", int_cols)
print("Object columns:", obj_cols)

Integer columns: []
Object columns: ['Time_Orderd', 'Weatherconditions', 'Road_traffic_density', 'Festival', 'City']

C:\Users\Divya S. Shekhawat\AppData\Local\Temp\ipykernel_11856\3147074763.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df[null_cols].select_dtypes(include=['object']).columns.tolist()

In [70]:
null_percentage = (
    df.isnull().mean() * 100
).reset_index()

null_percentage.columns = ['Column', 'Null_Percentage']

print(null_percentage)

                         Column  Null_Percentage
0                            ID         0.000000
1            Delivery_person_ID         0.000000
2           Delivery_person_Age         0.000000
3       Delivery_person_Ratings         0.000000
4           Restaurant_latitude         0.000000
5          Restaurant_longitude         0.000000
6    Delivery_location_latitude         0.000000
7   Delivery_location_longitude         0.000000
8                    Order_Date         0.000000
9                   Time_Orderd         3.796635
10            Time_Order_picked         0.000000
11            Weatherconditions         1.351085
12         Road_traffic_density         1.318185
13            Vehicle_condition         0.000000
14                Type_of_order         0.000000
15              Type_of_vehicle         0.000000
16          multiple_deliveries         0.000000
17                     Festival         0.500077
18                         City         2.631983
19              Time_taken(min)         0.000000

In [71]:
df.select_dtypes(include="object").columns

C:\Users\Divya S. Shekhawat\AppData\Local\Temp\ipykernel_11856\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['ID', 'Delivery_person_ID', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Type_of_order', 'Type_of_vehicle', 'Festival', 'City'],
      dtype='str')

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  float64
 3   Delivery_person_Ratings      45593 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  43862 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            44977 non-null  str
 12  Road_traffic_density         44992 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  float64
 17  Festival                     45365 non-null  str
 18  City                         44393 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.6 MB

In [78]:
null_cols = df.columns[df.isnull().any()].tolist()
# Categorical columns: fill missing values with the mode (most frequent category)
for col in null_cols:
  df[col] = df[col].fillna(df[col].mode()[0])

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  float64
 3   Delivery_person_Ratings      45593 non-null  float64
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  45593 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  float64
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  int64
dtypes: float64(7), int64(2), str(11)
memory usage: 10.6 MB

Exploratory data analysis

```Now the data is clean, we ask of every feature: what does its distribution look like, and does it actually relate to delivery time? For categorical features we compare the mean/median Time_taken(min) across groups; for numeric ones we look at trends.```

In [83]:
DATA_DIR = Path.cwd().parent

DATA_FOLD = DATA_DIR / "data" / "managed data"

# Create folder if it doesn't exist
DATA_FOLD.mkdir(parents=True, exist_ok=True)

# Save cleaned dataset
df.to_csv(DATA_FOLD / "cleaned_delivery_data.csv", index=False)